title: My Personal Site
description: A categorized knowledge base for study, work, and life
theme: jekyll-theme-slate
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

nav:
  - title: Home
    url: /
  - title: Study
    url: /study/
  - title: Job Experience
    url: /job/
  - title: Recipes
    url: /recipes/

social_links:
  - name: GitHub
    url: https://github.com/ltruong0
